name: Auto build archives

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-archives:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate auto archives
        run: node scripts/generate-auto-archives.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
